### ISSUE TITLE
Apparent typo in annotation name

### ISSUE THREAD

**Issue by plwhite** [k8snetworkplumbingwg/network-attachment-definition-client#17]
**What happend**:

Created some resources using multus and multiple networks. Annotations added to pods did not match spec.

**What you expected to happen**:

According to the spec (https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/)  this should lead to an annotation `k8s.v1.cni.cncf.io/network-status`, but it appeared that the annotation I got was `k8s.v1.cni.cncf.io/networks-status` (note the extra s to make it `networks`, not `network`).

That appears to be a simple typo in the code.

**Comment by phoracek** [comment]
CC @s1061123

**Comment by phoracek** [comment]
@plwhite thanks for reporting this. This repo follows the implementation from intel/multus-cni. I think it would be less disruptive to fix the document. Could you also raise it there?

**Comment by s1061123** [comment]
Thank you for the issue, @plwhite !
As far as I looked the code, 'networks-status' is used from initial commit of network status, so let's discuss about it in NPWG meeting.
https://github.com/intel/multus-cni/commit/8bb09518dfb3ccde0c4e0fc4a1579a1790858e77

**Comment by plwhite** [comment]
Fair enough - my instinct is just to change the spec now for consistency with the code.

**Comment by s1061123** [comment]
Folks,

I investigated the current implementations (as far as I know, only in Open Sourced) of NPWG Spec.
For now, tungsten(i.e. contrail) and CNI-Genie are using `k8s.v1.cni.cncf.io/network-status`.

- https://tungsten.io/
  - network-status is used at src/container/kube-manager/kube_manager/vnc/vnc_pod.py
  - added by [commit](https://github.com/Juniper/contrail-controller/commit/716bec006cbb1a3d64b7fb94c996407f9dbdb95d)
- https://github.com/cni-genie/CNI-Genie.git
  - network-status is used at genie/genie-controller.go
  - added by [commit](https://github.com/cni-genie/CNI-Genie/commit/43183345e598cd7300247466183514b5ff0b8d6b)
- https://github.com/ZTE/Knitter
  - network-status is not used!
- https://github.com/nokia/danm
  - network-status is not used!

So I suppose chaning NPWG lib (and multus) is the easy way than changing others.
Roughly I come up with the roadmap to fix the issue.

1. Add `k8s.v1.cni.cncf.io/network-status` into NPWG lib. During transitional phase, `k8s.v1.cni.cncf.io/networks-status` keeps in NPWG lib until next NPWG spec version-up
1. At the NPWG spec's next version-up, NPWG lib removes `k8s.v1.cni.cncf.io/networks-status`

How about that? Comments and questions are welcome.
If no objection, I will work on that.

**Comment by plwhite** [comment]
Works for me, thanks.
