### ISSUE TITLE
release 1.4.0 version

### ISSUE THREAD

**Issue by ykulazhenkov** [k8snetworkplumbingwg/network-attachment-definition-client#51]
Hi, 

I propose to release 1.4.0 version of network-attachment-definition-client with following content:

-  https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/42
-  https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/49

@adrianchiris @phoracek @dougbtv 
WDYT?

**Comment by adrianchiris** [comment]
+1,

This was also discussed in NPWG meeting on  Dec 1st

**Comment by dougbtv** [comment]
+1. Please go ahead with a new tag. Appreciate it!

**Comment by adrianchiris** [comment]
network-attachment-definition-client v1.4.0 release created. thx !
